
--求出各个部门薪资占比
SELECT T.*,
       SUM(T.SAL) OVER(PARTITION BY T.DEPTNO),
       SAL / SUM(T.SAL) OVER(PARTITION BY T.DEPTNO),
       RATIO_TO_REPORT(T.SAL) OVER(PARTITION BY T.DEPTNO)
  FROM TEST_V T;
